#!/bin/bash

export LC_CTYPE="en_US.UTF-8"
export FREETYPE_PROPERTIES="truetype:interpreter-version=35"

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

if [ -f "$BUNDLERESOURCEPATH/wine/bin/wine64" ]; then
    export WINEUSRPATH="$BUNDLERESOURCEPATH/wine"
fi

BUNDLE_VER="$(plutil -extract CFBundleIdentifier xml1 -o - "$BUNDLERESOURCEPATH/../Info.plist" | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")"
export WINEPREFIX="$HOME/Library/Application Support/${BUNDLE_VER}"
if [ ! -d "$WINEPREFIX" ]; then
	cp -R "$BUNDLERESOURCEPATH/wineprefix/." "$WINEPREFIX"
	xattr -rd com.apple.quarantine "$WINEPREFIX"
fi

#some default windows vars that might be missing ( http://ss64.com/nt/syntax-variables.html )
[ -z "$COMPUTERNAME" ] && export COMPUTERNAME="$(/usr/sbin/scutil --get ComputerName)"

BIN_FILE="C:/winbox/winbox64.exe"
BIN_PATH="$BUNDLERESOURCEPATH/wineprefix/drive_c$(sed 's|C:||' <<< "$(dirname "$BIN_FILE")")"
if [ -d "$BIN_PATH" ]; then
    cd "$BIN_PATH"
fi

DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"

"$WINEUSRPATH/bin/wine64" "$BIN_FILE"
