#!/bin/bash

export LC_CTYPE="en_US.UTF-8"
export FREETYPE_PROPERTIES="truetype:interpreter-version=35"

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

if [ -f "$BUNDLERESOURCEPATH/Wine.app/Contents/Resources/bin/wine64" ]; then
    export WINEUSRPATH="$BUNDLERESOURCEPATH/Wine.app/Contents/Resources"
fi

export WINEPREFIX="$HOME/Library/Application Support/$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleIdentifier)"
if [ ! -d "$WINEPREFIX" ]; then
    "$BUNDLERESOURCEPATH/Winetricks.app/Contents/MacOS/./Winetricks" "$BUNDLERESOURCEPATH/wineprefix" "$WINEPREFIX" "$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleName)" "WINEARCH=win64"
fi

#some default windows vars that might be missing ( http://ss64.com/nt/syntax-variables.html )
[ -z "$COMPUTERNAME" ] && export COMPUTERNAME="$(/usr/sbin/scutil --get ComputerName)"

BIN_FILE="C:/winebottler/winbox64.exe"
BIN_PATH="$BUNDLERESOURCEPATH/wineprefix/drive_c$(sed 's|C:||' <<< "$(dirname "$BIN_FILE")")"
if [ -d "$BIN_PATH" ]; then
    cd "$BIN_PATH"
fi

DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"

"$WINEUSRPATH/bin/wine64" "$BIN_FILE"
