#!/bin/bash

export LC_CTYPE="en_US.UTF-8"
export FREETYPE_PROPERTIES="truetype:interpreter-version=35"
export WINEDLLOVERRIDES="mscoree,mshtml="

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"
WINEUSRPATH="$BUNDLERESOURCEPATH/wine"

PLUTIL_REGEX="s/.*<string>\(.*\)<\/string>.*/\1/p"
CURRENT_VER="$(plutil -extract CFBundleIdentifier xml1 -o - "$BUNDLERESOURCEPATH/../Info.plist" | sed -n "$PLUTIL_REGEX")"

export WINEPREFIX="$HOME/Library/Application Support/${CURRENT_VER}"

"$WINEUSRPATH/bin/wine64" "$BUNDLERESOURCEPATH/winbox64.exe"

