#!/usr/bin/env arch -x86_64 bash
if [ -z "$LANG" ];then
    APP_PATH="$(dirname "$0")/../../"
    APPLE_LANG="$(osascript -e 'return user locale of (get system info)')"
    LANG="$APPLE_LANG.UTF-8" open -n $APP_PATH
    exit 0
fi;

export LC_CTYPE="$LANG"
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG="fixme-esync"

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

# workaround for https://bugs.winehq.org/show_bug.cgi?id=49199
# not needed in Gcenx build
# export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib"

PLUTIL_REGEX="s/.*<string>\(.*\)<\/string>.*/\1/p"
BUNDLE_ID="$(plutil -extract CFBundleIdentifier xml1 -o - "$BUNDLERESOURCEPATH/../Info.plist" | sed -n "$PLUTIL_REGEX")"

export WINEPREFIX="$HOME/Library/Application Support/${BUNDLE_ID}"

cd "$BUNDLERESOURCEPATH"
"$BUNDLERESOURCEPATH/wine/bin/wine64" "Z:\\$BUNDLERESOURCEPATH/winbox64.exe" "$@"