#!/usr/bin/env arch -x86_64 bash

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

PLUTIL_REGEX="s/.*<string>\(.*\)<\/string>.*/\1/p"
BUNDLE_ID="$(plutil -extract CFBundleIdentifier xml1 -o - "$BUNDLERESOURCEPATH/../Info.plist" | sed -n "$PLUTIL_REGEX")"

export WINEPREFIX="$HOME/Library/Application Support/${BUNDLE_ID}"

cd "$BUNDLERESOURCEPATH"

export PATH="$BUNDLERESOURCEPATH/wine/bin:$PATH"

if [ ! -f "$WINEPREFIX/font-smooth.fix" ];then
    "$BUNDLERESOURCEPATH/wine/bin/wine64" start regedit.exe "Z:\\$BUNDLERESOURCEPATH/patch/fontsmoothing.reg"
    echo > "$WINEPREFIX/font-smooth.fix"
fi;

"$BUNDLERESOURCEPATH/wine/bin/wine64" "Z:\\$BUNDLERESOURCEPATH/winbox64.exe" "$@"