#!/bin/bash

export LC_CTYPE="en_US.UTF-8"
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG="fixme-esync"

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

# workaround for https://bugs.winehq.org/show_bug.cgi?id=49199
# not needed in Gcenx build
export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib64"

PLUTIL_REGEX="s/.*<string>\(.*\)<\/string>.*/\1/p"
BUNDLE_ID="$(plutil -extract CFBundleIdentifier xml1 -o - "$BUNDLERESOURCEPATH/../Info.plist" | sed -n "$PLUTIL_REGEX")"

export WINEPREFIX="$HOME/Library/Application Support/${BUNDLE_ID}"

cd "$BUNDLERESOURCEPATH"
"$BUNDLERESOURCEPATH/wine/bin/wine64" "winbox64.exe" "$@"
